//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRI.Jab.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRI.Jab.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageNotFound {
            get {
                object obj = ResourceManager.GetObject("imageNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindrical Equal Area.
        /// </summary>
        public static string srs_ceaSubTitle {
            get {
                return ResourceManager.GetString("srs_ceaSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindrical Equal Area.
        /// </summary>
        public static string srs_ceaTitle {
            get {
                return ResourceManager.GetString("srs_ceaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string srs_defaultLatitude {
            get {
                return ResourceManager.GetString("srs_defaultLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string srs_defaultLongitude {
            get {
                return ResourceManager.GetString("srs_defaultLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string srs_defaultX {
            get {
                return ResourceManager.GetString("srs_defaultX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string srs_defaultY {
            get {
                return ResourceManager.GetString("srs_defaultY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84.
        /// </summary>
        public static string srs_geodeticDmsSubTitle {
            get {
                return ResourceManager.GetString("srs_geodeticDmsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84 (dms).
        /// </summary>
        public static string srs_geodeticDmsTitle {
            get {
                return ResourceManager.GetString("srs_geodeticDmsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84.
        /// </summary>
        public static string srs_geodeticSubTitle {
            get {
                return ResourceManager.GetString("srs_geodeticSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84 (decimal degree).
        /// </summary>
        public static string srs_geodeticTitle {
            get {
                return ResourceManager.GetString("srs_geodeticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercator.
        /// </summary>
        public static string srs_mercatorSubTitle {
            get {
                return ResourceManager.GetString("srs_mercatorSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercator.
        /// </summary>
        public static string srs_mercatorTitle {
            get {
                return ResourceManager.GetString("srs_mercatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transeverse Mercator.
        /// </summary>
        public static string srs_tmSubTitle {
            get {
                return ResourceManager.GetString("srs_tmSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transeverse Mercator.
        /// </summary>
        public static string srs_tmTitle {
            get {
                return ResourceManager.GetString("srs_tmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string srs_utmSubTitle {
            get {
                return ResourceManager.GetString("srs_utmSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Transeverse Mercator (UTM).
        /// </summary>
        public static string srs_utmTitle {
            get {
                return ResourceManager.GetString("srs_utmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap whiteImage {
            get {
                object obj = ResourceManager.GetObject("whiteImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
