//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRI.Maptor.Jab.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRI.Maptor.Jab.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Point.
        /// </summary>
        public static string draw_addPointText {
            get {
                return ResourceManager.GetString("draw_addPointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Drawing.
        /// </summary>
        public static string draw_cancelDrawingText {
            get {
                return ResourceManager.GetString("draw_cancelDrawingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Drawing Part.
        /// </summary>
        public static string draw_finishDrawingPartText {
            get {
                return ResourceManager.GetString("draw_finishDrawingPartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Drawing.
        /// </summary>
        public static string draw_finishDrawingText {
            get {
                return ResourceManager.GetString("draw_finishDrawingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the last point to finish drawing..
        /// </summary>
        public static string draw_newDrawingText {
            get {
                return ResourceManager.GetString("draw_newDrawingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        public static string goto_dialogTitle {
            get {
                return ResourceManager.GetString("goto_dialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageNotFound {
            get {
                object obj = ResourceManager.GetObject("imageNotFound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        public static string map_pan {
            get {
                return ResourceManager.GetString("map_pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To.
        /// </summary>
        public static string map_zoomTo {
            get {
                return ResourceManager.GetString("map_zoomTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Point.
        /// </summary>
        public static string mapPanel_currentPoint {
            get {
                return ResourceManager.GetString("mapPanel_currentPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi part.
        /// </summary>
        public static string mapPanel_multiPart {
            get {
                return ResourceManager.GetString("mapPanel_multiPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Reference System.
        /// </summary>
        public static string mapPanel_srs {
            get {
                return ResourceManager.GetString("mapPanel_srs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindrical Equal Area.
        /// </summary>
        public static string srs_ceaSubTitle {
            get {
                return ResourceManager.GetString("srs_ceaSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindrical Equal Area.
        /// </summary>
        public static string srs_ceaTitle {
            get {
                return ResourceManager.GetString("srs_ceaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string srs_defaultLatitude {
            get {
                return ResourceManager.GetString("srs_defaultLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string srs_defaultLongitude {
            get {
                return ResourceManager.GetString("srs_defaultLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        public static string srs_defaultX {
            get {
                return ResourceManager.GetString("srs_defaultX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        public static string srs_defaultY {
            get {
                return ResourceManager.GetString("srs_defaultY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84.
        /// </summary>
        public static string srs_geodeticDmsSubTitle {
            get {
                return ResourceManager.GetString("srs_geodeticDmsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84 (dms).
        /// </summary>
        public static string srs_geodeticDmsTitle {
            get {
                return ResourceManager.GetString("srs_geodeticDmsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84.
        /// </summary>
        public static string srs_geodeticSubTitle {
            get {
                return ResourceManager.GetString("srs_geodeticSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geodetic, WGS84 (decimal degree).
        /// </summary>
        public static string srs_geodeticTitle {
            get {
                return ResourceManager.GetString("srs_geodeticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercator.
        /// </summary>
        public static string srs_mercatorSubTitle {
            get {
                return ResourceManager.GetString("srs_mercatorSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercator.
        /// </summary>
        public static string srs_mercatorTitle {
            get {
                return ResourceManager.GetString("srs_mercatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transeverse Mercator.
        /// </summary>
        public static string srs_tmSubTitle {
            get {
                return ResourceManager.GetString("srs_tmSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transeverse Mercator.
        /// </summary>
        public static string srs_tmTitle {
            get {
                return ResourceManager.GetString("srs_tmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTM.
        /// </summary>
        public static string srs_utmSubTitle {
            get {
                return ResourceManager.GetString("srs_utmSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Transeverse Mercator (UTM).
        /// </summary>
        public static string srs_utmTitle {
            get {
                return ResourceManager.GetString("srs_utmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string srs_utmZone {
            get {
                return ResourceManager.GetString("srs_utmZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Mercator.
        /// </summary>
        public static string srs_webMercatorSubTitle {
            get {
                return ResourceManager.GetString("srs_webMercatorSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Mercator.
        /// </summary>
        public static string srs_webMercatorTitle {
            get {
                return ResourceManager.GetString("srs_webMercatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string symbology_fillLabel {
            get {
                return ResourceManager.GetString("symbology_fillLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke.
        /// </summary>
        public static string symbology_strokeLabel {
            get {
                return ResourceManager.GetString("symbology_strokeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke width.
        /// </summary>
        public static string symbology_strokeWidthLabel {
            get {
                return ResourceManager.GetString("symbology_strokeWidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Symbology.
        /// </summary>
        public static string symbology_title {
            get {
                return ResourceManager.GetString("symbology_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlackWhite.
        /// </summary>
        public static string tile_mapType_BlackWhite {
            get {
                return ResourceManager.GetString("tile_mapType_BlackWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CleanGrey.
        /// </summary>
        public static string tile_mapType_CleanGrey {
            get {
                return ResourceManager.GetString("tile_mapType_CleanGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic.
        /// </summary>
        public static string tile_mapType_Comic {
            get {
                return ResourceManager.GetString("tile_mapType_Comic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string tile_mapType_Dark {
            get {
                return ResourceManager.GetString("tile_mapType_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HikeBike.
        /// </summary>
        public static string tile_mapType_HikeBike {
            get {
                return ResourceManager.GetString("tile_mapType_HikeBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string tile_mapType_Hybrid {
            get {
                return ResourceManager.GetString("tile_mapType_Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string tile_mapType_Light {
            get {
                return ResourceManager.GetString("tile_mapType_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapyTourist.
        /// </summary>
        public static string tile_mapType_MapyTourist {
            get {
                return ResourceManager.GetString("tile_mapType_MapyTourist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapyWinter.
        /// </summary>
        public static string tile_mapType_MapyWinter {
            get {
                return ResourceManager.GetString("tile_mapType_MapyWinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        public static string tile_mapType_Nature {
            get {
                return ResourceManager.GetString("tile_mapType_Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NeutralBlue.
        /// </summary>
        public static string tile_mapType_NeutralBlue {
            get {
                return ResourceManager.GetString("tile_mapType_NeutralBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoadMap.
        /// </summary>
        public static string tile_mapType_RoadMap {
            get {
                return ResourceManager.GetString("tile_mapType_RoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string tile_mapType_Satellite {
            get {
                return ResourceManager.GetString("tile_mapType_Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string tile_mapType_Street {
            get {
                return ResourceManager.GetString("tile_mapType_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        public static string tile_mapType_Terrain {
            get {
                return ResourceManager.GetString("tile_mapType_Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topo.
        /// </summary>
        public static string tile_mapType_Topo {
            get {
                return ResourceManager.GetString("tile_mapType_Topo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic.
        /// </summary>
        public static string tile_mapType_Traffic {
            get {
                return ResourceManager.GetString("tile_mapType_Traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watercolor.
        /// </summary>
        public static string tile_mapType_Watercolor {
            get {
                return ResourceManager.GetString("tile_mapType_Watercolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BING.
        /// </summary>
        public static string tile_provider_bing {
            get {
                return ResourceManager.GetString("tile_provider_bing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARTO.
        /// </summary>
        public static string tile_provider_carto {
            get {
                return ResourceManager.GetString("tile_provider_carto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOGLE.
        /// </summary>
        public static string tile_provider_google {
            get {
                return ResourceManager.GetString("tile_provider_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPBOX.
        /// </summary>
        public static string tile_provider_mapbox {
            get {
                return ResourceManager.GetString("tile_provider_mapbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOKIA.
        /// </summary>
        public static string tile_provider_nokia {
            get {
                return ResourceManager.GetString("tile_provider_nokia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPENSTREETMAP.
        /// </summary>
        public static string tile_provider_osm {
            get {
                return ResourceManager.GetString("tile_provider_osm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAZE.
        /// </summary>
        public static string tile_provider_waze {
            get {
                return ResourceManager.GetString("tile_provider_waze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YANDEX.
        /// </summary>
        public static string tile_provider_yandex {
            get {
                return ResourceManager.GetString("tile_provider_yandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shapefile.
        /// </summary>
        public static string ui_addShapefile {
            get {
                return ResourceManager.GetString("ui_addShapefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Maps.
        /// </summary>
        public static string ui_baseMaps {
            get {
                return ResourceManager.GetString("ui_baseMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ui_clear {
            get {
                return ResourceManager.GetString("ui_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawings.
        /// </summary>
        public static string ui_drawings {
            get {
                return ResourceManager.GetString("ui_drawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Point.
        /// </summary>
        public static string ui_drawPoint {
            get {
                return ResourceManager.GetString("ui_drawPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Polygon.
        /// </summary>
        public static string ui_drawPolygon {
            get {
                return ResourceManager.GetString("ui_drawPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Polyline.
        /// </summary>
        public static string ui_drawPolyline {
            get {
                return ResourceManager.GetString("ui_drawPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Extent.
        /// </summary>
        public static string ui_fullExtent {
            get {
                return ResourceManager.GetString("ui_fullExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        public static string ui_goTo {
            get {
                return ResourceManager.GetString("ui_goTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string ui_layers {
            get {
                return ResourceManager.GetString("ui_layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Area.
        /// </summary>
        public static string ui_measureArea {
            get {
                return ResourceManager.GetString("ui_measureArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Length.
        /// </summary>
        public static string ui_measureLength {
            get {
                return ResourceManager.GetString("ui_measureLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap whiteImage {
            get {
                object obj = ResourceManager.GetObject("whiteImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
