// <auto-generated />
namespace IRI.Ket.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _13960726 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13960726));
        
        string IMigrationMetadata.Id
        {
            get { return "201710181325185_1396.07.26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
