name: NuGet Package Publisher (IRI Projects)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  NUGET_SOURCE: 'https://api.nuget.org/v3/index.json'
  PROJECT_PREFIXES: 'IRI.Sta IRI.Ket IRI.Jab'

jobs:
  build-and-publish:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    
    - name: Cache .NET
      uses: actions/cache@v3
      with:
        path: |
          ~/.dotnet
          ~/.nuget/packages
        key: ${{ runner.os }}-dotnet-${{ env.DOTNET_VERSION }}-${{ hashFiles('**/global.json') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-${{ env.DOTNET_VERSION }}-
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: |
        $prefixes = "${{ env.PROJECT_PREFIXES }}".Split(' ')
        foreach ($prefix in $prefixes) {
          Get-ChildItem -Path . -Recurse -Filter "${prefix}*.csproj" | ForEach-Object {
            dotnet restore $_.FullName
          }
        }
    
    - name: Build
      run: |
        $prefixes = "${{ env.PROJECT_PREFIXES }}".Split(' ')
        foreach ($prefix in $prefixes) {
          Get-ChildItem -Path . -Recurse -Filter "${prefix}*.csproj" | ForEach-Object {
            dotnet build $_.FullName --configuration Release --no-restore
          }
        }
    
    - name: Run tests
      run: |
        $prefixes = "${{ env.PROJECT_PREFIXES }}".Split(' ')
        foreach ($prefix in $prefixes) {
          Get-ChildItem -Path . -Recurse -Filter "${prefix}*.csproj" | Where-Object { $_.FullName -match '\.Tests\\' } | ForEach-Object {
            dotnet test $_.FullName --configuration Release --no-build --verbosity normal
          }
        }
    
    - name: Pack
      run: |
        New-Item -ItemType Directory -Force -Path ./nupkgs | Out-Null
        $prefixes = "${{ env.PROJECT_PREFIXES }}".Split(' ')
        foreach ($prefix in $prefixes) {
          Get-ChildItem -Path . -Recurse -Filter "${prefix}*.csproj" | Where-Object { $_.FullName -notmatch '\.Tests\\' } | ForEach-Object {
            dotnet pack $_.FullName --configuration Release --no-build --output ./nupkgs
          }
        }
    
    - name: Publish to NuGet
      if: github.ref == 'refs/heads/master'
      run: |
        $apiKey = "${{ secrets.NUGET_API_KEY }}"
        $prefixes = "${{ env.PROJECT_PREFIXES }}".Split(' ')
        foreach ($prefix in $prefixes) {
          Get-ChildItem -Path ./nupkgs -Filter "${prefix}*.nupkg" | ForEach-Object {
            dotnet nuget push $_.FullName --source ${{ env.NUGET_SOURCE }} --api-key $apiKey --skip-duplicate
          }
        }
       
